### ISSUE TITLE
Feature Request: add the simpliest realization of PXE server to devstation

### ISSUE THREAD

**Issue by mrPsycho** [Thinstation/thinstation#135]
why? 
for easier testing and demo tasks.

**Comment by Doncuppjr** [comment]
DevStation already allows booting the images via PXE, just point clients at it with your dhcp server.

**Comment by mrPsycho** [comment]
hm... but how to check it? 
are there any logs?

for example, im using zentyal... and configured it to use devstation as TFTP server with syslinux.0 file. 

and see no result :(

**Comment by Thinstation** [comment]
You would want to use pxelinux.0, not syslinux.0. Check /var/log/messages. 

    On Tuesday, April 12, 2016 3:30 PM, Yaroslav Nakonechnikov <notifications@github.com> wrote:
 

 hm... but how to check it? 
are there any logs?for example, im using zentyal... and configured it to use devstation as TFTP server with syslinux.0 file. and see no result :( —
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub 

   

A lightning fast message from Yahoo Mail. Get it now    On Tuesday, April 12, 2016 3:30 PM, Yaroslav Nakonechnikov <notifications@github.com> wrote:
 

 hm... but how to check it? 
are there any logs?for example, im using zentyal... and configured it to use devstation as TFTP server with syslinux.0 file. and see no result :( —

**Comment by mrPsycho** [comment]
yes! i found it! thanks a lot!


shame on meee!
