### ISSUE TITLE
Rebuild cups and freerdp packages

### ISSUE THREAD

**Issue by trentasis** [Thinstation/thinstation#137]
Actual 5.4 branch has a broken cups and freerdp compilation, please recompile , I think that my commit are not correctly generated, local update working, but after to commit in github and doing git clone then we receive "Could not find an archive" in cups and freerdp, 

Sorry for this mistake

Thanks

**Comment by Doncuppjr** [comment]
Recompile the archives, then git add them, make new pull request.


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by trentasis** [comment]
tried without success not updated after many attempts...
Sorry...
correct steps ?

**Comment by Thinstation** [comment]
git add -A ts/portsgit commit 

    On Tuesday, April 12, 2016 2:36 PM, trentasis <notifications@github.com> wrote:
 

 tried without success not updated after many attempts...
Sorry...
correct steps ?—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub 

   

A lightning fast message from Yahoo Mail. Get it now    On Tuesday, April 12, 2016 2:36 PM, trentasis <notifications@github.com> wrote:
 

 tried without success not updated after many attempts...
Sorry...
correct steps ?—

**Comment by trentasis** [comment]
ok, I'll try in  my local environment with my fork, but I 'm not sure to make test with master branch, I think that could be better to ensure a corrected build... can you rebuild this time? Next time I'll try to have more knowledge with git management... Sorry
I

**Comment by Doncuppjr** [comment]
You almost had it. Wrong git pkg was commited, cups was o.k.


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by trentasis** [comment]
Sorry Don... , now working
thanks for all and  great job!
