### ISSUE TITLE
Thinstation PCOIP 

### ISSUE THREAD

**Issue by Hyde94** [Thinstation/thinstation#227]
Hello,

I'm new on thinstation. I tried to configure a thinstation's session for horizon view with PCoIP. After a problems with the package vmviewpcoip which it was'nt inclued, I've had the link one the builds.urls files (param vmviewpcoipurl    https://download3.vmware.com/software/view/viewclients/CART17Q1/VMware-Horizon-Client-4.4.0-5167967.x86.bundle) and it's work normally. 

All the params that I need are ok but when I want to connect myself to a vdi session which the configured session, an error message display that the display protocol is not available. 
I supposed that view use blast instead of PCoIP and I can't find a param to verify/change this.

I hope that my resquest is understandable. 
Thanks in advance for your help.

**Comment by Hyde94** [comment]
So... I found something! 
I think that thinstation 5.5 doesn't work wih the last version of vmware horizon client. So I was obliged to create a new devstation (because when I change somthing in builds.urls, it doesn't work) and change the vmviewpcoipurl line with the vmview 3.5 link.

**Comment by Doncuppjr** [comment]
There is an issue with the latest horizon client, and the version of glibc that TS ships with. Working on it. Workaround is to put a newer libc next to the horizon binary. 

    On Wednesday, June 21, 2017 8:32 AM, Hyde94 <notifications@github.com> wrote:
 

 So... I found something!
I think that thinstation 5.5 doesn't work wih the last version of vmware horizon client. So I was obliged to create a new devstation (because when I change somthing in builds.urls, it doesn't work) and change the vmviewpcoipurl line with the vmview 3.5 link.—

**Comment by Hyde94** [comment]
Good to know. Thanks for this information. :)
