### ISSUE TITLE
NET configuration not parsed from thinstation.conf.user

### ISSUE THREAD

**Issue by pzradio** [Thinstation/thinstation#252]
Hi Folks,

Excellent project - a little hacky, just the way I like it :)

I'm trying to automate a fixed IP address "offline" build (i.e must always work in the absence of DHCP/web server/tftp server) for ~40 thinstations. It will be a build image flashed to a local drive with an automated RDP login, USB device mappings etc.

I have a working test buildtime config that does everything beautifully. The problem is then automating that for 40 stations. The example configs states that all NET directives need to go in buildtime, and I'd rather not have to build 40 images to achieve this.

Questions...
1) If a thinstation can get a network config off a server, and when it does, is it stored locally "forever", in case the server is not available? (Doesn't this sound a bit backwards as networkmanager is going to need to DHCP itself to talk a server, then reconfigure itself? Does it do this every time?)
2) Have there been any (undocumented) changes that lets us put NET directives in the user config?

If neither of the above....
I'm guessing I am going to need to hack the necessary data into the build, and make changes to the networkmanager script and where it gets its data from. I can put a list of all the hardware/IP addresses inside the build to achieve this.
3) Does this sound like a reasonable approach?
-or-
4) Has anyone else worked around the buildtime networking requirement successfully? 
Feedback appreciated :)

Cheers,

Peter Z

**Comment by Doncuppjr** [comment]
There is a simpler solution.
You can pass TS environment variables via the kernel command line. For a usb or hd installation, this would be stored in syslinux.cfg. You could customize just this text file on each workstation, with it's unique IP. You would only have to build one image with all the common options baked in, but pass the individual IP in via the kernel cmd line. 
    On Tuesday, November 7, 2017, 10:48:00 AM PST, pzradio <notifications@github.com> wrote:  
 
 
Hi Folks,

Excellent project - a little hacky, just the way I like it :)

I'm trying to automate a fixed IP address "offline" build (i.e must always work in the absence of DHCP/web server/tftp server) for ~40 thinstations. It will be a build image flashed to a local drive with an automated RDP login, USB device mappings etc.

I have a working test buildtime config that does everything beautifully. The problem is then automating that for 40 stations. The example configs state that all NET directives need to go in buildtime, and I'd rather not have to build 40 images to achieve this.

Questions...
   
   - If a thinstation can get a network config off a server, and when it does, is it stored locally "forever", in case the server is not available? (Doesn't this sound a bit backwards as networkmanager is going to need to DHCP itself to talk a server, then reconfigure itself? Does it do this every time?)
   - Have there been any (undocumented) changes that lets us put NET directives in the user config?

If neither of the above....
I'm guessing I am going to need to hack the necessary data into the build, and make changes to the networkmanager script and where it gets its data from. I can put a list of all the hardware/IP addresses inside the build to achieve this.
3) Does this sound like a reasonable approach?
-or-
4) Has anyone else worked around the buildtime networking requirement successfully?
Feedback appreciated :)

Cheers,

Peter Z

**Comment by pzradio** [comment]
Cheers - and apologies; After adding syslinux to my search terms, Google pulled your similar responses out of the Sourceforge mailinglists.

I've updated the installer script so it hacks in the options into syslinux, but it doesn't appear to like me adding lots of parameters to APPEND in syslinux.cfg, and defaults back to DHCP. I've manually appended the following "required" settings as a test: -
NET_USE_DHCP=Off NET_USE=LAN NET_HOSTNAME=TS-10 NET_IP_ADDRESS=192.168.0.110 NET_MASK=255.255.255.0 NET_GATEWAY=192.168.0.1 NET_DNS1=192.168.0.56 NET_DNS2=192.168.1.56

Will report back once I've worked out why its breaking.

**Comment by Thinstation** [comment]
Yes, there is a limit to how much can be shoved into the cmd line. You should put all common elements in thinstation.conf.buildtime, and only put the unique element in the cmdline, like the IP address. 

Also, networkmanager uses slight more specific variables, like NET_IPV4_ADDRESS. It looks like your using autonet variables, which never accommodated IPV6.

**Comment by Doncuppjr** [comment]
It might also make sense to put a ip lookup table into the image, and write an init script that parses hardware address for an ip address. This might be the cleanest solution, but the feature does not yet exist.

**Comment by Doncuppjr** [comment]
And do we bake the table into the image, or make it external? How do we keep it in sync? What IP would a client start with, if they were new to the network, and did not have a copy of the table yet?

**Comment by pzradio** [comment]
Thanks for the ideas, folks.
Networkmanager is included as a package, but I stripped out the buildtime parameters. I assumed startup would use autonet. I will try passing Networkmanager parameters in syslinux instead.

The way I've been doing this so far is to create a script on my boot stick that prompt the user for info before burning the image the image to disk. It appends syslinux.cfg with unique info like IP and hostname based on input.

Going forward, my approach will be to centrally manage and maintain a thinstation.conf.netstatic file which gets included when you build/update.
As a start, it will have hardware address, IP, and hostname information. It will get referenced to append/overwrite buildtime parameters when network config occurs. In my case, as suggested, common infrastructure parameters can stay in buildtime.
Going forwards, it will work with both network booted devices, and manual installs.

Not the best way, but its certainly convenient: -
1) Update station list
2) Build new image
opt) Write new image to build stick(s)

**Comment by pzradio** [comment]
..after much head scratching as to why any parameters passed through syslinux.cfg were not being applied...

NET_IPV4_ADDRESS wasn't being used, even though it was listed in "set" from a debug command prompt.

I found that NetworkManager's nmcreatesystemconn script requires python. Python isn't listed as a package in build.conf.example which I used as a base. Nor is it referenced in the vmware machine (or my own custom machines).

Might be worth putting python in as a core package :)
Cheers.

**Comment by Thinstation** [comment]
I will certainly look at adding the dep. Actually, figured that would have already been done.

**Comment by Thinstation** [comment]
Perhaps, since everybody is going to be static, you want to use autonet
instead of networkmanager?

**Comment by Thinstation** [comment]
Odd, including all of python just to generate a uuid. What a waste. Changed the script to use the util-linux uuidgen instead.
