### ISSUE TITLE
Thinclient image doesn't syn with my NTP Server

### ISSUE THREAD

**Issue by MAnnass** [Thinstation/thinstation#270]
When i boot my image from a bootserver the time lags atleast 2 hours behind when i wait a little bit (around 5-10minutes) it synchronize. Anyone an idea how to solve this problem?

In the build.conf
I have the package ntp enabled

In the thinstation.conf.buildtime 
i have 2 ntp servers enabled
NET_TIME_SERVER=win-**01.corp.*******.nl
NET_TIME_SERVER_BACKUP=win-**02.corp.*******.nl

**Comment by Thinstation** [comment]
Something you might only see migrating a machine from Windows to Linux or one time zone to another. In order to keep boot times down, ntp is initiated as a back ground process. Additionally, the Hardware RTC is only updated every couple of hours. During boot, the OS takes a reading from the RTC. This is the time that you see when you first boot. If it’s wrong, time will appear to be incorrect. When NTP syncs, system time is updated, but not RTC. If you power cycled, you would again have the wrong time. After a couple of hours of normal operation, RTC will be updated, and time discrepancies should disappear for all but the most meticulous.
