### ISSUE TITLE
FATAL: kernel too old on CentOS

### ISSUE THREAD

**Issue by TomAdriaensen** [Thinstation/thinstation#336]
I'm trying to set up a Centos server in the Google Cloud Platform with Thinstation.
First CentOS 7, but the same with 6.
I followed https://github.com/ThinStation/thinstation/wiki/Getting-Started-with-ThinStation 
these steps:
sudo su - 
yum install git
git clone --depth 1 git://github.com/Thinstation/thinstation.git -b 6.1-Stable
cd thinstation
./setup-chroot

Then I get the message:
FATAL: kernel too old

**Comment by Doncuppjr** [comment]
Did you install a 32 bit version of Centos?

Sent from Yahoo Mail for iPhone


On Wednesday, September 12, 2018, 2:25 AM, TomAdriaensen <notifications@github.com> wrote:


I'm trying to set up a Centos server in the Google Cloud Platform with Thinstation.
First CentOS 7, but the same with 6.
I followed https://github.com/ThinStation/thinstation/wiki/Getting-Started-with-ThinStation
these steps:
sudo su -
yum install git
git clone --depth 1 git://github.com/Thinstation/thinstation.git -b 6.1-Stable
cd thinstation
./setup-chroot

Then I get the message:
FATAL: kernel too old

**Comment by TomAdriaensen** [comment]
No, the standard 64-bits version.
CentOS 6:
cat /proc/version 
Linux version 2.6.32-754.3.5.el6.x86_64 (mockbuild@x86-01.bsys.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4
.7-23) (GCC) ) #1 SMP Tue Aug 14 20:46:41 UTC 2018
CentOS 7: 
cat /proc/version 
Linux version 3.10.0-862.11.6.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8
.5-28) (GCC) ) #1 SMP Tue Aug 14 21:49:04 UTC 2018

**Comment by Thinstation** [comment]
So that kernel is really old. Upgrade to the elrepo kernel

sudo rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
sudo rpm -Uvh http://elrepo.org/linux/kernel/el7/x86_64/RPMS/elrepo-release-7.0.3.el7.elrepo.noarch.rpm
sudo yum --enablerepo=elrepo-kernel install kernel-ml
sudo reboot
sudo grub2-set-default 0
sudo reboot
sudo yum -y remove kernel
cd /
sudo git clone --depth 1 https://github.com/Thinstation/thinstation
cd thinstation
sudo ./setup-chroot
