### ISSUE TITLE
Install 6.1 on VM - not able to go graphical

### ISSUE THREAD

**Issue by Seg22** [Thinstation/thinstation#346]
Hey There,

I´m still using 5.5 and it worked grate for me but no i need to get 6.1 working because of the new kernel.
I´m booting my vm with the iso TS-6.1.1-Installer-1122 and keep getting the error message: 

"The system was not able to go graphical. This could indicate a problem with missing kernel modules or Xorg drivers."

If i boot the vm with the 5.5 iso it works fine. If i boot the 6.1 iso on a real client it works too.
I´m using XenServer 7.1 build 137272c with no dedicated graphic card. The vm got 2 cores and 8gb ram.

If you need more informations please tel me.

Thanks in advance

Serge

**Comment by Doncuppjr** [comment]
What kind of video card does it emulate? How much video ram did you allocate.


Sent from Yahoo Mail for iPhone


On Tuesday, November 27, 2018, 2:02 AM, Seg22 <notifications@github.com> wrote:


Hey There,

I´m still using 5.5 and it worked grate for me but no i need to get 6.1 working because of the new kernel.
I´m booting my vm with the iso TS-6.1.1-Installer-1122 and keep getting the error message:

"The system was not able to go graphical. This could indicate a problem with missing kernel modules or Xorg drivers."

If i boot the vm with the 5.5 iso it works fine. If i boot the 6.1 iso on a real client it works too.
I´m using XenServer 7.1 build 137272c with no dedicated graphic card. The vm got 2 cores and 8gb ram.

If you need more informations please tel me.

Thanks in advance

Serge

**Comment by Seg22** [comment]
Hey Doncuppjr,

i´m using the integrated GPU from Xeon E3-1225 V2, i dont have any chance to change settings for the gpu, neither the card it emulates nor the video ram allocated.
Or maybe i just don´t see it.

**Comment by Doncuppjr** [comment]
I’m talking about the VM. Most hypervisors let you control how much video memory is assigned to the vm.


Sent from Yahoo Mail for iPhone


On Tuesday, November 27, 2018, 11:51 PM, Seg22 <notifications@github.com> wrote:


Hey Doncuppjr,

i´m using the integrated GPU from Xeon E3-1225 V2, i dont have any chance to change settings for the gpu, neither the card it emulates nor the video ram allocated.
Or maybe i just don´t see it.

**Comment by Seg22** [comment]
I´m talking about the vm, too. You don´t have any chance to change or see the vram in xencenter, sorry.

**Comment by Thinstation** [comment]
Looks like it's configured via CLI. I found this article that should help. Try 16mb.

https://www.citrix.com/blogs/2014/05/12/from-my-virtual-desktop-using-standard-vga-instead-of-cirrus/

**Comment by Seg22** [comment]
Oh thanks for the advice, didn´t know that. Unfortunatelly it doesn´t work tho. Tried 16mb and 4 mb, still same issue. Anyway i´m now using Hyper-V and it works, if you want me to try something else to solve the issue just tell me but i need it to work now and i´m fine with Hyper-V.

**Comment by Doncuppjr** [comment]
I need the Xorg.0.log to figure out why it didn’t load.


Sent from Yahoo Mail for iPhone


On Thursday, November 29, 2018, 12:08 AM, Seg22 <notifications@github.com> wrote:


Oh thanks for the advice, didn´t know that. Unfortunatelly it doesn´t work tho. Tried 16mb and 4 mb, still same issue. Anyway i´m now using Hyper-V and it works, if you want me to try something else to solve the issue just tell me but i need it to work now and i´m fine with Hyper-V.

**Comment by Seg22** [comment]
Could export the file so here in screenshots sorry [https://imgur.com/a/fTEJVvw](url)

**Comment by Thinstation** [comment]
I think I have this fixed now.
