### ISSUE TITLE
New install of Thinstation dev no TFTP server installed

### ISSUE THREAD

**Issue by Aurthuric** [Thinstation/thinstation#357]
I just installed thinstation dev on a computer.  I am attempting to use it as the PXE server for booting systems with a thinclient os.  However, 
/etc/init.d/xinetd init comes back with no file found xinetd
So this tells me that the TFTP server is not installed.

TFTP clients are timing out on connection to the server which supports my hypothesis.  I am new to linux and thinstation so please help.

**Comment by Thinstation** [comment]
We are no longer reliant upon xinetd to run the tftp server. Instead, atftp is running in daemon mode as a systemd service. I might still convert that into a socket, but for now it's a daemon.

**Comment by Aurthuric** [comment]
Ok.  So that is why I cannot find the xinet, but when I port scan the server, I do not see port 69, my TFTP client cannot access tit and PWE boot times out in trying to open the TFTP connection.  How can I correct this?

**Comment by Doncuppjr** [comment]
What is the output of “ps x |grep -e inet" and "ps x |grep -e ftp"

Sent from Yahoo Mail for iPhone


On Thursday, January 24, 2019, 5:23 AM, Aurthuric <notifications@github.com> wrote:


Ok. So that is why I cannot find the xinet, but when I port scan the server, I do not see port 69, my TFTP client cannot access tit and PWE boot times out in trying to open the TFTP connection. How can I correct this?

**Comment by Aurthuric** [comment]
The results of:  “ps x |grep -e inet" are 3904 root     0:00 Grep -e Inet
The results of : "ps x |grep -e ftp"1577  ATFTP     0:00 /usr/sbin/atftpd  -- user=atftp atftp - - daemon -- no-fork -- no-multicast --maxthread 20 --verbose=6 /var/lib/tftpboot
3910 root      0:00 grep -e ftp

**Comment by Thinstation** [comment]
Everything looks good to me
