### ISSUE TITLE
Automount Issue, misprint command, udisks2 conflict

### ISSUE THREAD

**Issue by Se7ven** [Thinstation/thinstation#362]
https://github.com/Thinstation/thinstation/blob/9a3c978e694c409fb6ad71ccb68d8949919c0c52/ts/build/packages/automount/etc/udev/scripts/scsi.sh#L62
instead of
`systemd-mount -u --no-block $mtdpath`

Second one thing:
https://github.com/Thinstation/thinstation/blob/9a3c978e694c409fb6ad71ccb68d8949919c0c52/ts/build/packages/automount/etc/udev/scripts/scsi.sh#L71
I think it's conflict with gvfs-udisks2-volume-monitor
Maybe change the conditional operator parameter to 
`pgrep udisksd`
to avoid conflict with udisks package?

**Comment by Doncuppjr** [comment]
Nice finds , changes pushed.
    On Wednesday, February 13, 2019, 5:09:30 AM PST, Se7ven <notifications@github.com> wrote:  
 
 
https://github.com/Thinstation/thinstation/blob/9a3c978e694c409fb6ad71ccb68d8949919c0c52/ts/build/packages/automount/etc/udev/scripts/scsi.sh#L62
instead of
systemd-mount -u --no-block $mtdpath

Second one thing:
https://github.com/Thinstation/thinstation/blob/9a3c978e694c409fb6ad71ccb68d8949919c0c52/ts/build/packages/automount/etc/udev/scripts/scsi.sh#L71
I think it's conflict with gvfs-udisks2-volume-monitor
Maybe change the conditional operator parameter to
pgrep udisksd
to avoid conflict with udisks package?

**Comment by Se7ven** [comment]
> Nice finds , changes pushed. On Wednesday, February 13, 2019, 5:09:30 AM PST, Se7ven 

Emm
`systemed-mount -u $mtdpath`
syste**md**

`busybox pgrep udisks2`
Find gvfs-udisks2-volume-monitor which not conflicted with automount.
But needs to find `udisksd`.

**Comment by Thinstation** [comment]
Oky doky.
