### ISSUE TITLE
package debug without effect in 6.1.1

### ISSUE THREAD

**Issue by streetworkr** [Thinstation/thinstation#415]
I am trying to debug a problem I am having with a custom package and tried 
the package debug.
During build I see an error 

`
Package: debug
Not Found debug!!
`
but from reading other posts I understand, that this can be ignored because debug is a metapackage.

Still, I don't  see any difference between activating or not activating debug.
Is this still supposed to work?

**Comment by Doncuppjr** [comment]
Package debug would bring in extensions and extensions-x. So really it's just setting you up to debug, not actually debugging. An O/S is a slightly huge thing to turn on global debugging output. You might try narrowing your focus a little.
    On Friday, May 10, 2019, 2:08:32 AM PDT, streetworkr <notifications@github.com> wrote:  
 
 
I am trying to debug a problem I am having with a custom package and tried
the package debug.
During build I see an error

Package: debug Not Found debug!!
but from reading other posts I understand, that this can be ignored because debug is a metapackage.

Still, I don't see any difference between activating or not activating debug.
Is this still supposed to work?

**Comment by streetworkr** [comment]
I was referring to this section in the Debugging page of the wiki:

> Include the debug package
> Rebuild your image with
> 
> package debug
>
> Note: with debug included your startup will ALWAYS stop after system initiation, so that you can either > look at debug information or press enter to continue into the sessions. Remove the debug package 
> when you have finished.

which I could not observe.

I also tried using `DEBUGPAUSE=true` together with `package debug`, but that didn't work either.

**Comment by Thinstation** [comment]
Ahhh, that section most certainly needs an update. Or I have to
re-implement that feature, as systemd changed a lot of startup behavior.

**Comment by Thinstation** [comment]
This might be better.
