### ISSUE TITLE
TS 6.1 USB mount fail

### ISSUE THREAD

**Issue by mcsn747** [Thinstation/thinstation#458]
I builded previous productive Thinstation image with vmview client 4.10 in july. In this build the USB devices does connect automatically.
Now i tried build a new thinstation image with same vmview client 4.10. The USB devices don't work as expected. They autoconnect only if inserted at startup. I don't changed my custom settings for vmview.

I compare logs from old and new images and see that the unit mnt-usbdevice-sda*.mount is in the failed state.
[journalctl-usb-old.txt](https://github.com/Thinstation/thinstation/files/3634278/journalctl-usb-old.txt)
[journalctl-usb-new.txt](https://github.com/Thinstation/thinstation/files/3634279/journalctl-usb-new.txt)

**Comment by Doncuppjr** [comment]
Do you have automount package enabled?

**Comment by mcsn747** [comment]
Yes.

**Comment by Doncuppjr** [comment]
Im not sure why the mount is in a failed state. Do you have the correct modules for file-systems loaded, so that systemd can mount the file-system? Is the usb redirector grabbing the device before it can be mounted and then being shared with the remote machine? What is the complete behavior pattern you are trying to recreate or debug?

**Comment by mcsn747** [comment]
I think you may close this issue. When I cloned repo again I have USB automount worked. It's look like a temporary bug.
