### ISSUE TITLE
10GB git?

### ISSUE THREAD

**Issue by KingOfDos** [Thinstation/thinstation#54]
Ur doing it WRONG!

**Comment by gcscaglia** [comment]
Sorry for necroing this issue, but what KingOfDos means is that instead of versioning packages binaries, you should version scripts which downloads and extracts the packages (from their repository, specifying the version; This way you can still track changes), and have their extracted contents in your `.gitignore`.

That's how dependency management works when you use things like maven for java, pip for python, gems for ruby, etc. Since on Thinstation case there is no equivalent, writing you own is the way to go.

Currently, thinstation .gitignore files are, at best, insufficient. As soon as you run `setup-chroot`, `git status` reports lots of untracked files; This shouldn't be the case.

**Comment by Thinstation** [comment]
That is a common anti-pattern, but I do not wish to sustain it.

**Comment by gcscaglia** [comment]
I see, you do understand what we mean, but you do not agree with it. That's a perfectly fine view point; there is more than one way to do things. Never mind me then.

But what about the current `.gitignore`? Since a fresh setup-chroot already has lots of untracked files, It becomes quite cumbersome to keep track of what we actually added. Is there a particular rationale and/or workflow which justifies the current `.gitignore`?

**Comment by Doncuppjr** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } I never really intended for such a thing to exist, it was a contribution that didn't get in my way, so it was allowed. I run clean_chroot before doing a status or commit. A time consuming operation, but when you need orientation, it works. Very destructive, use at your own risk.


Sent from Yahoo Mail for iPhone


On Friday, June 23, 2017, 9:34 AM, gcscaglia <notifications@github.com> wrote:


I see, you do understand what we mean, but you do not agree with it. That's a perfectly fine view point; there is more than one way to do things. Never mind me then.

But what about the current .gitignore? Since a fresh setup-chroot already has lots of untracked files, It becomes quite cumbersome to keep track of what we actually added. Is there a particular rationale and/or workflow which justifies the current .gitignore?

**Comment by gcscaglia** [comment]
I see, that certainly works too, despite the caveats you already mentioned.

Never mind that as well. Ty for your attention.

**Comment by Doncuppjr** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Np, feel free to improve .gitignore generation logic. 


Sent from Yahoo Mail for iPhone


On Friday, June 23, 2017, 9:50 AM, gcscaglia <notifications@github.com> wrote:


I see, that certainly works too, despite the caveats you already mentioned.

Never mind that as well. Ty for your attention.
