### ISSUE TITLE
Intel NUC still can't boot UEFI

### ISSUE THREAD

**Issue by maa7** [Thinstation/thinstation#586]
I already wrote about it: https://github.com/Thinstation/thinstation/issues/506
but issue still present with latest build..

**Comment by Thinstation** [comment]
The kernel that works on NUC doesnt work well everywhere else..... Very annoying. I don't know why yet, but I am investigating.

**Comment by Thinstation** [comment]
Sooooo. I played with this quite a bit. Sadly, any kernel that works on June Canyon is not reliable anywhere else, and crashes for sure on Apple. I need to distribute the most compatible kernel possible with with my distro, that's why I stopped pushing the one that works with that NUC. I can make aux kernel config, but that's not intuitive to admins...the target for my distro. I'll let you know if I come up with something.
