### ISSUE TITLE
Global Network Config PXE Boot 0.0.0.0

### ISSUE THREAD

**Issue by Snify89** [Thinstation/thinstation#720]
I am using TS 5.6 
and have the following packages enabled/disabled:

package netfiles
package networkmanager
package udisks
#package udisks-glue
#package ts-classic

built in the image (build.conf) and can boot via PXE

I have also added the following in the thinstation.conf.buildtime

NET_FILE_ENABLED=On
NET_FILE_METHOD=tftp

anything else is left by default such as 
NET_USE=BOTH
NET_USE_DHCP=on

The PXE booting works fine from the tftp server.
However, when Thinstation tries to load the global config file (thinstation.conf.network - in a ts5.6 subdirectory), it fails because it tries to load from the IP-Address "0.0.0.0"

I thought, that it would load the config files via tftp from the current DHCP settings, or am I missing something?

The fallback to the default thinstation.conf.buildtime works fine, after the failed attempt to load the thinstation.conf.network 

Thank you in advance for your help.

**Comment by Doncuppjr** [comment]
netfiles wont work with networkmanager, you need autonet






On Monday, May 2, 2022, 01:01:23 AM PDT, Snify89 ***@***.***> wrote: 







I am using TS 5.6
and have the following packages enabled/disabled:

package netfiles
package networkmanager
package udisks
#package udisks-glue
#package ts-classic

built in the image (build.conf) and can boot via PXE

I have also added the following in the thinstation.conf.buildtime

NET_FILE_ENABLED=On
NET_FILE_METHOD=tftp

anything else is left by default such as
NET_USE=BOTH
NET_USE_DHCP=on

The PXE booting works fine from the tftp server.
However, when Thinstation tries to load the global config file (thinstation.conf.network - in a ts5.6 subdirectory), it fails because it tries to load from the IP-Address "0.0.0.0"

I thought, that it would load the config files via tftp from the current DHCP settings, or am I missing something?

The fallback to the default thinstation.conf.buildtime works fine, after the failed attempt to load the thinstation.conf.network

Thank you in advance for your help.

**Comment by Snify89** [comment]
I can't find a package named autonet in Devstation 5.6
Is this included in the ts-classic package?

**Comment by Doncuppjr** [comment]
Yes.






On Monday, May 2, 2022, 11:10:34 PM PDT, Snify89 ***@***.***> wrote: 







I can't find a package named autonet in Devstation 5.6
Is this included in the ts-classic package?
