### ISSUE TITLE
splash screen not shut down correctly?!?

### ISSUE THREAD

**Issue by jens-maus** [Thinstation/thinstation#73]
Since a few weeks we are having trouble with some of our thin clients using thinstation (HZDR fork). The problem users were reporting is that they could not press "F2" as they will always end up in the splash screen being displayed without being able to exit that situation.

After some investigation we found that the splash screen daemon (fbsplashd) is still running for these systems and as soon as we did a remote ssh connection the splash screen immediately disappeared. After further investigation we found that within /etc/profile the exit of splash screen is enforced by explicitly calling 'splash_exit'. That's the reason why the splash screen disappears when login in via ssh.

After some more investigation we finally added a workaround to our startup script by explicitly sending an "exit" command to the fbsplash daemon via its fifo pipe. This workaround is shown here:

https://github.com/hzdr/thinstation/commit/512b81e36124b0de1182f79e59d7afc3dabfd596

Now everything works as expected and the F2 key is not reserved for switching to/from the splash screen. They question remains, however, why this happens. To me it seems to be a runtime problem as some client are more prone to this problem than others. In addition, the problem didn't exist several weeks ago when we did our last official HZDR-fork release (1.7). In fact, at the end of April it seems everything was still working fine without having this F2 problem.

**Comment by Thinstation** [comment]
Fixed. Using privilege separation and non-root user caused the splash pid test to fail.

**Comment by trentasis** [comment]
Hi,

I have detected that since we are using thinstation 5.x, during boot when appears a message with "Press F2 " to show boot messages this doesn't work when keyboard is USB, but using ps/2 keyboard works always... we have tested with multiple machiens and keyboards and this fails when you boot with usb keyboard.

Is this the same problem reported in this issue?
Do you know where could be the problem?

I was using thinstation 2.2 and this was working perfect

Thanks

**Comment by Doncuppjr** [comment]
This might be a localization issue. What is the language of the keyboard, what locale are you using?


Sent from Yahoo Mail for iPhone


On Friday, July 28, 2017, 4:04 AM, trentasis <notifications@github.com> wrote:


Hi,

I have detected that since we are using thinstation 5.x, during boot when appears a message with "Press F2 " to show boot messages this doesn't work when keyboard is USB, but using ps/2 keyboard works always... we have tested with multiple machiens and keyboards and this fails when you boot with usb keyboard.

Is this the same problem reported in this issue?
Do you know where could be the problem?

I was using thinstation 2.2 and this was working perfect

Thanks

**Comment by trentasis** [comment]
Hi,

I'm using spanish, and I have configured only spanish locale. If you give
some indication where could be the issue, I'll try to debug

Thanks

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-07-28 13:41 GMT+02:00 Donald A. Cupp Jr. <notifications@github.com>:

**Comment by Doncuppjr** [comment]
I have not seen this with English keyboard and en_US locale. Do you have access to a USB English keyboard?


Sent from Yahoo Mail for iPhone


On Friday, July 28, 2017, 6:55 AM, trentasis <notifications@github.com> wrote:

Hi,

I'm using spanish, and I have configured only spanish locale. If you give
some indication where could be the issue, I'll try to debug

Thanks

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-07-28 13:41 GMT+02:00 Donald A. Cupp Jr. <notifications@github.com>:

**Comment by trentasis** [comment]
OK, I'll try to test your suggestion, If this is the problem, where is this
configuration?
Thanks!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-07-28 15:56 GMT+02:00 Donald A. Cupp Jr. <notifications@github.com>:

**Comment by trentasis** [comment]
opened an issue https://github.com/Thinstation/thinstation/issues/240, is not the same issue
