### ISSUE TITLE
Latest ThinStation installer ISO lets you end up with an empty root shell

### ISSUE THREAD

**Issue by MathijsG** [Thinstation/thinstation#763]
I downloaded TS-6.2.13-Installer-0311.iso from https://kumisystems.dl.sourceforge.net/project/thinstation/thinstation/thinstation-6/TS-6.2.13-Installer-0311.iso

First tried Ventoy/Easy2Boot but I ended up in a empty root shell, instead of some installer environment/wizard.

Burnt the ISO on CD, but now I end up with the same:

![image](https://user-images.githubusercontent.com/529552/216018693-6ca438da-3afb-4cd8-8e6e-7ac41d033bbe.png)

When I see other issues and google searches on "DevStation" I get something like this: https://github.com/Thinstation/thinstation/issues/248

But here nothing graphical starts.

Specs:

Wyse Dx0D

Processor
   Type
   Speed	Dual core AMD G-T48E
1.4GHz
Memory
   Flash
   RAM	  2GB
  2GB (max 8GB)
Video
   Chip
   Max resolution	AMD Radeon HD 6250 Graphics
2560 x 1600 32-bit colour (Display Port)
1920 x 1200 32 bit colour (DVI-I port)
1920x1200 32-bit colour (Dual display)
Ports
   Video
   Network
   USB
   Serial
   Parallel
   PS/2	1 x DVI-I, 1 x Display Port
10/100/1000
4 x USB2.0

**Comment by Doncuppjr** [comment]
You don’t run DevStation on a thin client. Make a VM or use a computer with at least 4gb of RAM. Build images that will run on a thin client. Watch the video.


Sent from Yahoo Mail for iPhone


On Wednesday, February 1, 2023, 2:34 AM, Mathijs Groothuis ***@***.***> wrote:




I downloaded TS-6.2.13-Installer-0311.iso from https://kumisystems.dl.sourceforge.net/project/thinstation/thinstation/thinstation-6/TS-6.2.13-Installer-0311.iso

First tried Ventoy/Easy2Boot but I ended up in a empty root shell, instead of some installer environment/wizard.

Burnt the ISO on CD, but now I end up with the same:



When I see other issues and google searches on "DevStation" I get something like this: #248

But here nothing graphical starts.

Specs:

Wyse Dx0D

Processor
Type
Speed Dual core AMD G-T48E
1.4GHz
Memory
Flash
RAM 2GB
2GB (max 8GB)
Video
Chip
Max resolution AMD Radeon HD 6250 Graphics
2560 x 1600 32-bit colour (Display Port)
1920 x 1200 32 bit colour (DVI-I port)
1920x1200 32-bit colour (Dual display)
Ports
Video
Network
USB
Serial
Parallel
PS/2 1 x DVI-I, 1 x Display Port
10/100/1000
4 x USB2.0

**Comment by MathijsG** [comment]
So no generic images that you can just write or install onto the thin client directly? Like every modern distribution like Ubuntu for example? Okay I will try it out in a vm then

**Comment by Thinstation** [comment]
I never saw the point of making something exactly like someone else. I have
incorporated some stuff that requires more memory than regular distros. It
‘can’ make things go faster.

**Comment by MathijsG** [comment]
Okay, then I didn't understand the purpose, my bad. Will dive into the image creation, thanks for the directions.
