### ISSUE TITLE
DevStation Building multiple RDP/Citrix ThinStation Clients fails 

### ISSUE THREAD

**Issue by OperationJosef** [Thinstation/thinstation#777]
Hello all, 

currently I have the problem and the task to create Thinclients, how simple Thinstation is described it is not at all.
About the documentation I do not even want to start felt only 15% of the whole topic is covered. 

I have left as much as possible to the standard in the Build.conf except that I have selected/added RDesptop and ICA.
So far everything seems to run perfectly when I DON'T select ICA. 

As soon as I add ICA to the selection I get the following error message at the end when running ./build :

...............................................................................
gtk-engines: Setup complete

gtk-theme-adwaita: Setup complete

gtkdialog: Setup complete

INSTALLING ICA

cp: cannot stat '//downloads/linuxx64-21.12.0.18.tar.gz': No such file or directory

Error has occured copying file

Build Aborted

Script done on 2023-07-10 02:12:34-07:00 [COMMAND_EXIT_CODE="1"]

..........................................................................................................................................................................................................................................................

I downloaded this version from the Citrix website: linuxx64-23.7.0.17.tar.gz apparently there is an old version somewhere in the configuration. I can not find it and would be grateful if someone can tell me what I have to adjust where so that I finally find a starting point for my concern.

**Comment by Doncuppjr** [comment]
ICA is proprietary software. We make it easy to mix in, but you will need to download yourself from Citrix after agreeing to their licensing.


Sent from Yahoo Mail for iPhone


On Monday, July 10, 2023, 3:28 AM, OperationJosef ***@***.***> wrote:




Hello all,

currently I have the problem and the task to create Thinclients, how simple Thinstation is described it is not at all.
About the documentation I do not even want to start felt only 15% of the whole topic is covered.

I have left as much as possible to the standard in the Build.conf except that I have selected/added RDesptop and ICA.
So far everything seems to run perfectly when I DON'T select ICA.

As soon as I add ICA to the selection I get the following error message at the end when running ./build :

...............................................................................
gtk-engines: Setup complete

gtk-theme-adwaita: Setup complete

gtkdialog: Setup complete

INSTALLING ICA

cp: cannot stat '//downloads/linuxx64-21.12.0.18.tar.gz': No such file or directory

Error has occured copying file

Build Aborted

Script done on 2023-07-10 02:12:34-07:00 [COMMAND_EXIT_CODE="1"]

..........................................................................................................................................................................................................................................................

I downloaded this version from the Citrix website: linuxx64-13.10.0.20.tar.gz apparently there is an old version somewhere in the configuration. I can not find it and would be grateful if someone can tell me what I have to adjust where so that I finally find a starting point for my concern.

**Comment by OperationJosef** [comment]
Hello, 

I downloaded it, the file name is linuxx64-23.7.0.17.tar.gz but the builder is looking for a linuxx64-21.12.0.18.tar.gz, so there seems to be a version difference. 

I have also packed the file under the intended download folder where the builder also has his downloaded chrome installation file. I have tested unnaming the file from linuxx64-23.7.0.17.tar.gz to linuxx64-21.12.0.18.tar.gz and it continued the step but still failed. I can't find the exact version the builder is looking for anywhere. I also can't find the place where I can change the version.

**Comment by Doncuppjr** [comment]
/build/build.urls

**Comment by OperationJosef** [comment]
Notes about build:

Kernel 5.15.51TS size is 8420K

Initrd size is 33690K

Squash size is 432520K



Build Complete!



Goodbye. 

___________________________



Worked like a charm !!! Thank you very much !

**Comment by OperationJosef** [comment]
After building the iso where is the output ? :)

**Comment by Doncuppjr** [comment]
/build/boot-images/grub/thinstaion-efi.iso


Sent from Yahoo Mail for iPhone


On Monday, July 10, 2023, 8:15 AM, OperationJosef ***@***.***> wrote:




After building the iso where is the output ? :)

**Comment by OperationJosef** [comment]
Thanks for helping ! No iam facing another issue, after using rufus to get the iso to a usb, i can only select UEFI, if i do so after loading the stick the screen just stays black. What am i possibly doing wrong ?

**Comment by Thinstation** [comment]
If this is your first build, you need to make an allmodules build. Until
you have fingerprinted the module set of your target machine, you will have
to make allmodules builds. Then figure out the best Xorg driver for your
target, then work on the application.

**Comment by OperationJosef** [comment]
So i could just enable all modules, rebuild and then try again? 

It is also tricky for me to get a copy of the iso because everything i normally try results in access denied

**Comment by Thinstation** [comment]
./build —allmodules, make hwlister is in the packages, and then you can
fingerprint the target. See WIKI

**Comment by OperationJosef** [comment]
This is not really clear for me, i tried to look this up on the wiki but i ended up having more questions then before. :( 
Would you guys please assist me threw the steps In brief highlights ?

**Comment by Thinstation** [comment]
If you look under /build/machine, you will see a bunch of machine profiles.
You need of those to make an optimal image. Use hwlister.sh to create the
files, transfer them to your build , make a profile .
