### ISSUE TITLE
PXE boot read only filesystem with squashfs init

### ISSUE THREAD

**Issue by matreicht** [Thinstation/thinstation#784]
Hi!
I am having issues trying to PXE boot on old hardware, if I use gzip as the initrdcmd parameter I get kernel panic but if I try squashfs the system boots but drops to shell because the file system is read only.
Is there any solution inbetween to keep the compression but get an rw file system?

**Comment by Doncuppjr** [comment]
When using squashfs, include the overlay package, and that will simulate rw.

Sent from Yahoo Mail for iPhone


On Wednesday, August 23, 2023, 3:22 AM, matreicht ***@***.***> wrote:




Hi!
I am having issues trying to PXE boot on old hardware, if I use gzip as the initrdcmd parameter I get kernel panic but if I try squashfs the system boots but drops to shell because the file system is read only.
Is there any solution inbetween to keep the compression but get an rw file system?

**Comment by matreicht** [comment]
Thank you for the quick response once again, it's working this way.
