### ISSUE TITLE
Problems with upgrade 2.2 to 5.4

### ISSUE THREAD

**Issue by trentasis** [Thinstation/thinstation#80]
We are tying to upgrade from thinstation 2.2 to latest 5.4 and we have detected some problems:

1.-  we use as ts workstation in session 0,and with thinstation 2.2 all boot log was recorded in ctrl+alt+f1, but with this version any is showed after the boot in f1 session, how can I do this?
2.-  we need to reduce as possible size and boot time, as similar as possible to 2.2 version. Now we are using xfce and rdesktop with hwlister, how can we reduce size and boot? Fastboot, initr compression,...? We only use thinstation as rdesktop client, and with new versions I'm not sure if we can disable any windowsmanager, icewm, xfwm, trueteype fonts in build.conf and only keep session_0 as rdesktop sessions with printers... we only need this..
3.-with package www we have an administartion site on port 6800 as it was described in 2.2, but with 5.4 without a shortcut to vnc remote control. We have enabled xorgvnc, how can we recover a shortcut from www to 5800 site?

Thanks

**Comment by Doncuppjr** [comment]
1. The log is available at /var/log/boot.log and /var/log/messages is also helpful.2. You can still put rdesktop as the only session and as session_0. Including xfwm4 enables extra features, like compositing and window resizing when running on a hyper-visor, but it is not necessary. 3. The process for using hwlister.sh is documented at the top of build.conf, and several times throughout the mailing list, but the thinking behind it is this. I and most people have no idea what modules are needed to make a given hardware setup operate optimally, but udev does a pretty good job(not perfect) of figuring this out for us. The more modules we include, the longer it takes the system to decompress and start, udev takes longer to run. So we want to fingerprint the actual modules that are needed for a given hardware config(s), and only include those modules in subsequent builds. We start by doing and allmodules/allfirmware build with hwlister.sh included. Boot the hardware(s), get a list of modules and firmwares that were actually loaded, and send those lists back to the build server, so that we no longer have to make allmod/allfirm builds. We make machine profiles out of each set of lists and include those machine profiles in build.conf. New builds still use udev for module loading, but they decompress a lot faster and udev runs a lot faster.4. I don't fully understand what you are asking for here. 


     On Saturday, July 25, 2015 8:35 AM, trentasis <notifications@github.com> wrote:
   

 We are tying to upgrade from thinstation 2.2 to latest 5.4 and we have detected some problems:1.- we use as ts workstation in session 0,and with thinstation 2.2 all boot log was recorded in ctrl+alt+f1, but with this version any is showed after the boot in f1 session, how can I do this?
2.- we need to reduce as possible size and boot time, as similar as possible to 2.2 version. Now we are using xfce and rdesktop with hwlister, how can we reduce size and boot? Fastboot, initr compression,...? We only use thinstation as rdesktop client, and with new versions I'm not sure if we can disable any windowsmanager, icewm, xfwm, trueteype fonts in build.conf and only keep session_0 as rdesktop sessions with printers... we only need this..
3.-with package www we have an administartion site on port 6800 as it was described in 2.2, but with 5.4 without a shortcut to vnc remote control. We have enabled xorgvnc, how can we recover a shortcut from www to 5800 site?Thanks—

**Comment by trentasis** [comment]
Hi, 

1.- I know that log is in boot.log and message, but with previous version (2.2) boot.log was printed to ctra+alt+f1 session, and now is not avaialble (only via cli), can we recover this features it is useful for  quicly debug...
2.-Thanks, I'll try to remove any windowsmanager and keep only rdesktop packages. About thinstation size, now we are using an image with xfwm and rdesktop and onlye 1 supported hardware (generated with hwlister.sh) and image size is 90Mb, but with previous versions size was 12MB, I'll try to remove unused features. 
It is recommended to use fastboot, change compression initrs or any other action to reduce size and time to boot thinstation 5.4?
3.- Sorry, with pakcage www with version 2.2 and http server was available with logs, general information, and remote control  (VNC session). With 5.4 we have configure xorgvnc but in www (on port 6800) remote control (url to vnc) has disappeared, how can we recover this option? It was removed?

Thanks

**Comment by Doncuppjr** [comment]
1. Change param bootverbosity to 72. For single purpose rdesktop image, you likely don't want to use fastboot. Increasing compression level will most likely slow you down and use more memory, which you may not have.3. I never used that feature, so I don't know when it broke or how long it will take to fix. 


     On Monday, July 27, 2015 2:02 AM, trentasis <notifications@github.com> wrote:
   

 Hi, 1.- I know that log is in boot.log and message, but with previous version (2.2) boot.log was printed to ctra+alt+f1 session, and now is not avaialble (only via cli), can we recover this features it is useful for quicly debug...
2.-Thanks, I'll try to remove any windowsmanager and keep only rdesktop packages. About thinstation size, now we are using an image with xfwm and rdesktop and onlye 1 supported hardware (generated with hwlister.sh) and image size is 90Mb, but with previous versions size was 12MB, I'll try to remove unused features. 
It is recommended to use fastboot, change compression initrs or any other action to reduce size and time to boot thinstation 5.4?
3.- Sorry, with pakcage www with version 2.2 and http server was available with logs, general information, and remote control (VNC session). With 5.4 we have configure xorgvnc but in www (on port 6800) remote control (url to vnc) has disappeared, how can we recover this option? It was removed?Thanks—

**Comment by Thinstation** [comment]
Is this issue resolved?

**Comment by trentasis** [comment]
1.- loglevel 3 is correct, with 7 more loglevel is showed during boot, but our problems is after a boot in ctr+alt+f1 we can't view loglevel of boot, how can recover this features that with 2.2 was working and now with 5.4 not?
2.- Thanks, I'll try to remove unused packages, widnwosmanager, fonts, ... to reduce size
3.- Can you detail where I can find source code ot this feature? I like to try to find where is the problem and compare with 2.2 version...

Thanks

**Comment by Doncuppjr** [comment]
Comment out line 27 of file ts/build/packages/base/etc/profile 


Sent from Yahoo Mail on Android

**Comment by trentasis** [comment]
1.- Perfect it was  this clear command, added this change as pull request, with previous versions was working
2.- Now making some test... evaluating
3.- We have made some modifications as pull request and now lshw is working but xorg7vnc linkg to admin is now working, we only can to work making:
- add pull requests with "if pkg_initialized x11vnc.init ; " and tehn rm /var/packages/www and /etc/init.d/www init after that it works... but I can't find why lshw appears and xorg7vnc not.. any help?

**Comment by trentasis** [comment]
3.- I have made some change but not working with xorg7vnc url, and lshw wotking... I can't find any difference.. Can you help?

Thanks

**Comment by trentasis** [comment]
Actual situation:
1.- Solved
2.- Reduced size without xfwm4, fonts,... Solved
3.- I can't find whay vns url is not showed in www, and lshw url is showed.... any help?

**Comment by trentasis** [comment]
3.- Solved error www, it was a boot  order problem with xorg7vnc, can you commit  pull request 100, contains a resolution

Thanks!
