### ISSUE TITLE
thinstation 6.2.14

### ISSUE THREAD

**Issue by clodoaldosimon** [Thinstation/thinstation#832]
Hello, in thinstation 6.2.14, after compiling by running ./build it no longer generates separate directories in /thinstation/build/boot-images/, can anyone help me? I need the files for PXE.

**Comment by Thinstation** [comment]
The grub image supports all modes of booting. You can look at the
deployment wiki page for more details. The boot file for bios is
boot/grub/pxeboot.img

**Comment by clodoaldosimon** [comment]
Hi, I understand, but in which directories are the pxe boot files generated?

**Comment by Doncuppjr** [comment]
/build/boot-images/grub/efi-source should be the root of your tftp serverboot/grub/pxeboot.img will be the boot file for BIOS, and EFI/boot/grubx64.efi is for EFI systems.
    On Friday, June 14, 2024 at 07:27:01 AM MDT, clodoaldosimon ***@***.***> wrote:  
 
 


Hi, I understand, but in which directories are the pxe boot files generated?

**Comment by clodoaldosimon** [comment]
Thanks for your help @Doncuppjr , I managed to solve it.

**Comment by rohrbachger** [comment]
Don,
I'm missing the ISO files generated in older versions.
Iḿ using this in an iPXE boot environment, to support easy assigning different thinstation builds on e.g. different hardware or different functionality. With an ISO that woks since 8 yeas fine..
I tried to figure out what the old script does, but before I spent days... 
Do you think it can be added as a special parameter for build? Or are there technical reasons this does not work anymore.
Most of the old machines I´m using still booting in BIOS mode , not UEFI. Some can, the most not.

**Comment by Thinstation** [comment]
What do you mean? The thinstation-efi.iso will boot in any mode. BIOS/EFI from HD BIOS/EFI from CD BIOS/EFI from PXE. ThinStation never provided the iPXE boot loader, but it never closed the door on it either. The main reason that I removed all of the other bootloaders, is that they are no longer supported by the people that made them. The syslinux project hasn't seen an update since 2017, and even that one was highly questionable. Development more or less stopped for them back in 2015. If you really need them. I can try and dig out the commits for you and you can reverse them, but grub should work for you on any machine. For PXE, point the boot file to boot/grub/pxeboot.img Deployment . Additionally, I have added a utility to configure DevStation as a router/dhcp/dns server. It already had tftp and webserver, now it's a complete solution to boot clients on a subnet.

**Comment by rohrbachger** [comment]
Thanks for explanation.
Your are right, it is booting with BIOS mode without any issue.
My misunderstanding, I thought thinstation-efi.iso will only boot with UEFI enabled.

That`s fine for me.
What did **not** worked on a Lenovo is, when I enabled UEFI boot, to load with iPXE.
I will try to figure out the reason, in the moment it's okay, in my environment every thinstation client is in BIOS mode.
The Lenovo booted the thinstation-efi.iso from CD, in UEFI Mode.
