### ISSUE TITLE
DevStation does not install.

### ISSUE THREAD

**Issue by ProgrammerVsita** [Thinstation/thinstation#833]
I tried versions TS-6.2.14-Installer-0619.iso and -1111.iso on ThinkPad L450 and I get this error: "During post install checks, we discovered /boot/boot/vmlinuz: missing. Your installation is not likely to work. Aborting!"
[install.log](https://github.com/user-attachments/files/15861027/install.log)
[https://github.com/Thinstation/thinstation/issues/528](url)
[installer.log](https://github.com/user-attachments/files/15861045/installer.log)

**Comment by Thinstation** [comment]
The download of the OS did not complete. Your behind an SSL firewall. 
Connecting to sourceforge.net (sourceforge.net)|10.20.250.252|:443... connected.WARNING: cannot verify sourceforge.net's certificate, issued by ***@***.***,CN=localhost,OU=IT Org,O=IT,L=Changsha,ST=Hunan,C=CN’:  Self-signed certificate encountered.    WARNING: certificate common name ‘localhost’ doesn't match requested host name ‘sourceforge.net’.
          thindev-d     [<=>                 ]       0  --.-KB/s               thindev-default-6.2     [ <=>                ]     781  --.-KB/s    in 0s      
2024-06-17 03:07:31 (59.4 MB/s) - ‘thindev-default-6.2.tar.xz’ saved [781]
    On Sunday, June 16, 2024 at 09:17:57 PM MDT, Vista ***@***.***> wrote:  
 
 


I tried versions TS-6.2.14-Installer-0619.iso and -1111.iso on ThinkPad L450 and I get this error: "During post install checks, we discovered /boot/boot/vmlinuz: missing. Your installation is not likely to work. Aborting!"
install.log
https://github.com/Thinstation/thinstation/issues/528
installer.log

**Comment by ProgrammerVsita** [comment]
> The download of the OS did not complete. Your behind an SSL firewall.  Connecting to sourceforge.net (sourceforge.net)|10.20.250.252|:443... connected.WARNING: cannot verify sourceforge.net's certificate, issued by ***@***.***,CN=localhost,OU=IT Org,O=IT,L=Changsha,ST=Hunan,C=CN’:  Self-signed certificate encountered.    WARNING: certificate common name ‘localhost’ doesn't match requested host name ‘sourceforge.net’.           thindev-d     [<=>                 ]       0  --.-KB/s               thindev-default-6.2     [ <=>                ]     781  --.-KB/s    in 0s       2024-06-17 03:07:31 (59.4 MB/s) - ‘thindev-default-6.2.tar.xz’ saved [781] On Sunday, June 16, 2024 at 09:17:57 PM MDT, Vista ***@***.***> wrote: I tried versions TS-6.2.14-Installer-0619.iso and -1111.iso on ThinkPad L450 and I get this error: "During post install checks, we discovered /boot/boot/vmlinuz: missing. Your installation is not likely to work. Aborting!" install.log #528 installer.log — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

So is it my network or firewall that's causing this issue?

**Comment by Thinstation** [comment]
Yes


Sent from Yahoo Mail for iPhone


On Sunday, June 16, 2024, 11:22 PM, Vista ***@***.***> wrote:





The download of the OS did not complete. Your behind an SSL firewall.  Connecting to sourceforge.net (sourceforge.net)|10.20.250.252|:443... connected.WARNING: cannot verify sourceforge.net's certificate, issued by @.,CN=localhost,OU=IT Org,O=IT,L=Changsha,ST=Hunan,C=CN’:  Self-signed certificate encountered.    WARNING: certificate common name ‘localhost’ doesn't match requested host name ‘sourceforge.net’.           thindev-d     [<=>                 ]       0  --.-KB/s               thindev-default-6.2     [ <=>                ]     781  --.-KB/s    in 0s       2024-06-17 03:07:31 (59.4 MB/s) - ‘thindev-default-6.2.tar.xz’ saved [781] On Sunday, June 16, 2024 at 09:17:57 PM MDT, Vista @.> wrote: I tried versions TS-6.2.14-Installer-0619.iso and -1111.iso on ThinkPad L450 and I get this error: "During post install checks, we discovered /boot/boot/vmlinuz: missing. Your installation is not likely to work. Aborting!" install.log #528 installer.log — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.***>


So is it my network or firewall that's causing this issue?

**Comment by ProgrammerVsita** [comment]
Because my network has limited access, now I can install ts normally after removing this restriction, thank you
