### ISSUE TITLE
sd card or usbdevice

### ISSUE THREAD

**Issue by trentasis** [Thinstation/thinstation#92]
We can upgrade Thinstation 5.4 because  TS5.4 and executing df -h any device is showed with our config, we use ts-classic, we have tried with default config build.conf and thinstation.conf.builtime from defautl config and with this config seems OK, appears /mnt/mnt/usbdevice/sda1 device but we can't fins where is the problem...
what package or config is needed to obtain mount point for sd card or usbdevices with df -h ?

Thanks

**Comment by Doncuppjr** [comment]
I'm not quite sure what you are trying to do here. I usally try and use the Volume Label to pick storage locations.
 


     On Thursday, September 24, 2015 7:47 AM, trentasis <notifications@github.com> wrote:
   

 We can upgrade Thinstation 5.4 because TS5.4 and executing df -h any device is showed with our config, we use ts-classic, we have tried with default config build.conf and thinstation.conf.builtime from defautl config and with this config seems OK, appears /mnt/mnt/usbdevice/sda1 device but we can't fins where is the problem...
what package or config is needed to obtain mount point for sd card or usbdevices with df -h ?Thanks—

**Comment by trentasis** [comment]
We only are tryingto upgrade with hdupdate a thinclient with sd card or usb device, and our problem is that any device is listed as device in df -h 
With sata disks works ok

We have tested with default config build and buildtiem from example and with this config works with /mnt/mnt/usbdevice/sda1 and we don't know what package is required to mount sdcard or usbdevice 

Thanks

**Comment by Doncuppjr** [comment]
Should just be automount, and the modules for whatever devices are in the chain like USB and scsimod


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by trentasis** [comment]
Thanks, the problemas was that module ums_realtek was not loaded.
Solved 

Thanks
